# -*- coding: utf-8 -*-
"""scraping-comment-tiktok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blllfjr0HcyceKSAN-Wuylrg3yDAO2vu
"""

!pip install google_play_scraper

from google_play_scraper import reviews, Sort

# Ganti dengan app ID Threads dari link yang lo kasih
app_ID = 'com.ss.android.ugc.trill'

# Ambil review terbaru
result, _ = reviews(
    app_ID,
    lang='id',       # Bahasa Indonesia
    country='id',    # Lokasi Indonesia
    sort=Sort.NEWEST,
    count=30000      # Jumlah review yang diambil
)

print(f"Jumlah data yang diambil: {len(result)}")

import pandas as pd

df_reviews = pd.DataFrame(result)
df_2024_2025 = df_reviews[(df_reviews['at'].dt.year == 2024) | (df_reviews['at'].dt.year == 2025)]
df_reviews.head()

df_reviews.info()

df_reviews.shape

df_reviews = df_reviews.drop_duplicates()

jumlah_ulasan, jumlah_kolom = df_reviews.shape
print("Jumlah Ulasan", jumlah_ulasan)
print("Jumlah Kolom", jumlah_kolom)

df = df_reviews

"""##**Preprocessing Data**"""

# Convert the 'at' column to datetime
df['at'] = pd.to_datetime(df['at'])

# Eksplorasi
print(f"Jumlah data 2024-2025: {len(df_2024_2025)}")
print("\nDistribusi rating:")
print(df_2024_2025['score'].value_counts())
print("\nMissing values:")
print(df_2024_2025.isnull().sum())
print("\nSampel teks:")
print(df_2024_2025['content'].head(10))

# Drop the specified columns
columns_to_drop = ['reviewId', 'userName', 'userImage', 'reviewCreatedVersion', 'replyContent', 'repliedAt', 'appVersion']
df = df.drop(columns=columns_to_drop)

# Verify the changes
print(df.info())

cleaned_df = df

cleaned_df.to_csv('labeling_data.csv', index=False)